apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: petlinic
  namespace: spring-demo
spec:
  routes:
  - services:
    - name: petclinic
      port: 80
  virtualhost:
    fqdn: petlinic.test.tanzutime.com
